### PR TITLE
ci: add Gitpod integration

### PR DESCRIPTION
**Pull request by davidaparicio**
Documentation: https://www.gitpod.io/docs/introduction/languages/java

### CODE REVIEW

**Comment by davidaparicio** [comment]
Related issue: https://github.com/dadoonet/fscrawler/issues/1591

**Review by dadoonet — COMMENTED** [review]
That looks great!

Wondering if the .gitpod yml file can be stored in .github instead. WDYT?

**Comment by davidaparicio** [comment]
Screenshot 2023-02-03 at 19 52 07

It looks, this file ```.gitpod``` is root repository only, currently....
https://www.gitpod.io/docs/references/gitpod-yml

**Review by dadoonet — APPROVED** [review]

**Comment by dadoonet** [comment]
Thanks!

**Pull request merged**
