### PR TITLE
Feature/adding yes flag

### PR DESCRIPTION
**Pull request by Rapalagui**
Adding "--yes" flag for the default "bin/fscrawler ${job_name}" cli command.
Similar to apt. This is a clean solution for Dockerfiles when trying to create a new job with specific predefined settings etc (CMD...).

### CODE REVIEW

**Comment by shahariaazam** [comment]
But if with `--yes` flag automatically create settings then how you will define the `directory`? Also I think we can if it can be like `--autocreate` or something understable would be great. It's just my own comments.

**Comment by Rapalagui** [comment]
> But if with `--yes` flag automatically create settings then how you will define the `directory`? Also I think we can if it can be like `--autocreate` or something understable would be great. It's just my own comments.

You are talking about autocreate a directory (like when creating a new job)?

**Comment by shahariaazam** [comment]
> > But if with `--yes` flag automatically create settings then how you will define the `directory`? Also I think we can if it can be like `--autocreate` or something understable would be great. It's just my own comments.
> 
> You are talking about autocreate a directory (like when creating a new job)?
> I will try to rename it and will take a look over it again.

Yeah. And the purpose of `--yes` was for that. Isn't it?

**Comment by Rapalagui** [comment]
I initially just wanted a simple flag to confirm the answer. But indeed I was wrong and didn't think about the full process :) I am currently just helping out a friend of mine. I will now go ahead to create the **entire** "autocreate" flag so the job will get build even if it doesn't exist yet. You are right!

**Comment by shahariaazam** [comment]
> I initially just wanted a simple flag to confirm the answer. But indeed I was wrong and didn't think about the full process :) I am currently just helping out a friend of mine. I will now go ahead to create the **entire** "autocreate" flag so the job will get build even if it doesn't exist yet. You are right!

Ok. I got it. But I think we should keep this issue open and wait for others to give feedback about we need it or not.

Because I have a point, if it gets auto created then stil in the settings file the directory path needs to be manually updated. Am I correct?

Also did you try `--silent` flag?  I didn't use it though. You can find details from https://fscrawler.readthedocs.io/en/latest/admin/cli-options.html#cli-options

**Comment by Rapalagui** [comment]
> > I initially just wanted a simple flag to confirm the answer. But indeed I was wrong and didn't think about the full process :) I am currently just helping out a friend of mine. I will now go ahead to create the **entire** "autocreate" flag so the job will get build even if it doesn't exist yet. You are right!
> 
> Ok. I got it. But I think we should keep this issue open and wait for others to give feedback about we need it or not.
> 
> Because I have a point, if it gets auto created then stil in the settings file the directory path needs to be manually updated. Am I correct?
> 
> Also did you try `--silent` flag? I didn't use it though. You can find details from https://fscrawler.readthedocs.io/en/latest/admin/cli-options.html#cli-options

Yeah, I am totally fine with that. I have seen this flag. `--silent` is just used for hiding the output is it? It will still "ask for a job to create" if it doensnt exist right? 

Yep you are right. I was thinking about using a flag when using Docker and mounting a configuration file to the job dir. The flag should be combined with `--config_dir` in my thoughts, so it doesn't (manually) ask to create a new job but just uses a predefined settings file and creates the job. (Am I getting something wrong and its already doing this?) 

BTW: I am using Docker (& Kubernetes) with [this](https://hub.docker.com/r/shadiakiki1986/fscrawler/) base image and split its docker-compose file up; Did some changes to the Dockerfile etc.

**Comment by Rapalagui** [comment]
> > I initially just wanted a simple flag to confirm the answer. But indeed I was wrong and didn't think about the full process :) I am currently just helping out a friend of mine. I will now go ahead to create the **entire** "autocreate" flag so the job will get build even if it doesn't exist yet. You are right!
> 
> Ok. I got it. But I think we should keep this issue open and wait for others to give feedback about we need it or not.
> 
> Because I have a point, if it gets auto created then stil in the settings file the directory path needs to be manually updated. Am I correct?
> 
> Also did you try `--silent` flag? I didn't use it though. You can find details from https://fscrawler.readthedocs.io/en/latest/admin/cli-options.html#cli-options

So, I have tried around some more with Docker. It seems to work like I want it already! Actually my configuration file mapping in the Dockerfile was wrong. I mounted the file directly under the config_dir. IMO, "autocreate" is not needed since we already can map a file - which will indeed get picked up by fscrawler. My bad!

**Comment by dadoonet** [comment]
That being said I found the discussion interesting. I mean that I'd like to propose a better starting experience. Like run everything from the CLI with few basic options like the path, elasticsearch url...

**Comment by shahariaazam** [comment]
> That being said I found the discussion interesting. I mean that I'd like to propose a better starting experience. Like run everything from the CLI with few basic options like the path, elasticsearch url...

Yeah it would be awesome. Lots of stuff can be made easier. For example, docker.

**Comment by dadoonet** [comment]
@shahariaazam Would you like to open an issue about it?

Ideally share what you would need as CLI parameters.

**Comment by shahariaazam** [comment]
> @shahariaazam Would you like to open an issue about it?
> 
> Ideally share what you would need as CLI parameters.

Yes of course. I can create an issue about this topics instead talking in this PR.

**Comment by dadoonet** [comment]
> Yes of course. I can create an issue about this topics instead talking in this PR.

Awesome! Thanks

**Comment by shahariaazam** [comment]
> > Yes of course. I can create an issue about this topics instead talking in this PR.
> 
> Awesome! Thanks

I just opened an issue. Shortly I will try to provide some helpful parameters in that issue.

**Comment by Rapalagui** [comment]
I'll definitely keep an eye on this!

**Comment by dminovski0** [comment]
> @shahariaazam Would you like to open an issue about it?
> 
> Ideally share what you would need as CLI parameters.

Did you add these options, to run the properties in the `_settings.yaml` file as CLI parameters?

**Comment by dadoonet** [comment]
I don't think we added anything yet to support those features.

**Pull request closed without merging**
