### PR TITLE
Use https protocol in local nodes per default

### PR DESCRIPTION
**Pull request by HansBambel**
In https://github.com/dadoonet/fscrawler/issues/1274#issuecomment-1764303125 it was noted that the default http protocol resulted in an error `Unexpected end of file from server`.

When switching to `https` the error does not occur.

With this PR the default protocol of a local node's url will be `https`.

The documentation was also updated to reflect that. I was not sure how to handle the text in the Note as it proposes to use HTTPS instead of HTTP, but now this is the default. Should it be omitted or kept to show the change from version 2.2?

**Important**
I don't know how to run the tests locally as I am not a Java developer and I also do not use elasticsearch, but opensearch (and even this not yet successfully).

### CODE REVIEW

**Comment by dadoonet** [comment]
The build issue is something I should fix. I'll try to work on this later today. ;)

**Comment by HansBambel** [comment]
Great, thanks!

**Comment by dadoonet** [comment]
@HansBambel could you rebase on master please? I'd like to see if the recent changes I did will work...

**Comment by HansBambel** [comment]
Sorry, I actually did a rebase, but when pulling again a merge was done by default :-/

If you want me to fix it, I can try to do that.

```
$ [Thu 19 8:21:16] (base)  ~/fscrawler (use-https-per-default) -> git rebase upstream/master
Successfully rebased and updated refs/heads/use-https-per-default.
$ [Thu 19 8:21:43] (base)  ~/fscrawler (use-https-per-default) -> git push
To https://github.com/HansBambel/fscrawler.git
 ! [rejected]          use-https-per-default -> use-https-per-default (non-fast-forward)
error: failed to push some refs to 'https://github.com/HansBambel/fscrawler.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
$ [Thu 19 8:21:53] (base)  ✘  ~/fscrawler (use-https-per-default) -> git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Merge made by the 'recursive' strategy.
$ [Thu 19 8:22:42] (base)  ~/fscrawler (use-https-per-default) -> git push
Enumerating objects: 37, done.
Counting objects: 100% (31/31), done.
Delta compression using up to 8 threads
Compressing objects: 100% (23/23), done.
Writing objects: 100% (23/23), 3.69 KiB | 3.69 MiB/s, done.
Total 23 (delta 14), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (14/14), completed with 6 local objects.
To https://github.com/HansBambel/fscrawler.git
   dd8aa245..9c04977c  use-https-per-default -> use-https-per-default
```

**Comment by dadoonet** [comment]
Weird. Apparently the new push did not trigger the CI. I'm going to check.

**Comment by HansBambel** [comment]
@dadoonet Done!

**Comment by dadoonet** [comment]
Could you rebase again? I'm trying to fix something../ If it fails again, I'll do the github actions changes in another repo... :)

**Comment by HansBambel** [comment]
Done :)

**Comment by dadoonet** [comment]
@HansBambel I think I fixed the problem in another repo and applied the changes here. Could you rebase again please?

I'm sorry for this :)

**Comment by HansBambel** [comment]
No problem :D 

Done 👍

**Review by dadoonet — APPROVED** [review]

**Comment by dadoonet** [comment]
Apparently some of the unit tests need to be fixed. Could you work on that @HansBambel?

**Comment by HansBambel** [comment]
@dadoonet Sorry, but it's been too long that dealt with Java (back in University). I don't even know where to start here.

If you help me to compile/run the code/tests I can have a look.

**Comment by dadoonet** [comment]
Thanks!

**Pull request merged**
