### PR TITLE
Document HTTP server and port

### PR DESCRIPTION
**Pull request by chrissound**
https://github.com/dadoonet/fscrawler/issues/727

### CODE REVIEW

**Comment by chrissound** [comment]
Hmm that option does not seem to work by me? I'm doing `mvn install -Dtests.rest.port=8123` and there isn't anything listening on port 8123, it fails with the previous error in the issue.

However if I terminate an unrelated program running on port 8080, it passes successfully.

**Comment by dadoonet** [comment]
That's definitely a bug in the tests. I'll try to fix it next week.

**Comment by dadoonet** [comment]
Good news. I finally found the bug. Fix is coming with #760. 
Could you add the change I mentioned then?

**Comment by chrissound** [comment]
Good to hear, just pushed the change. Thank you.

**Comment by NeerajSachdeva** [comment]
Seems like its port already occupied issue. Did any of you guys faced this issue on teamcity/jenkins/bamboo where mutliple people pushed code in their respective feature branches and then each branch is getting build and trying to use same port?

**Pull request merged**
